### ISSUE TITLE
[Feature Reqest] Anmelde Status -2 gibt auch AnmeldeID zurück

### ISSUE THREAD

**Issue by tobikrs** [EC-Nordbund/ec-api#13]
Bitte geben, wenn Person schon angemeldet ist auch die AnmeldeID zurück.

**Comment by mathe42** [comment]
Aktuell arbeite ich am rewrite mit async, await da baue ich das ein

**Comment by tobikrs** [comment]
Großartig!

**Comment by mathe42** [comment]
Schiebe die aktuelle dev Variante nach master... kannst dir ja mal den DIFF bei der anmeldung ansehen ;)
